In [2]:
import pandas as pd
import numpy as np
data = {
'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'Customer_Name': ['Amara', 'Bola', None, 'Diana', 'Efua', 'Fatima', 'Grace',
None, 'Ifeoma', 'Joyce'],
'Country': ['Ghana', 'Nigeria', 'Kenya', None, 'Ghana', 'Cameroon', None,
'Kenya', 'Nigeria', 'Ghana'],
'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', None, 'Phone', 'Tablet',
'Laptop', None, 'Phone'],
'Quantity': [2, 1, None, 3, 2, None, 1, 4, 2, None],
'Price': [1500, 800, 600, 1500, None, 800, 600, 1500, None, 800],
'Delivery_Days': [3, None, 7, 5, 3, None, 6, None, 4, 5]
}
df = pd.DataFrame(data)
print(df)

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop       2.0  1500.0            3.0
1       102          Bola   Nigeria   Phone       1.0   800.0            NaN
2       103          None     Kenya  Tablet       NaN   600.0            7.0
3       104         Diana      None  Laptop       3.0  1500.0            5.0
4       105          Efua     Ghana    None       2.0     NaN            3.0
5       106        Fatima  Cameroon   Phone       NaN   800.0            NaN
6       107         Grace      None  Tablet       1.0   600.0            6.0
7       108          None     Kenya  Laptop       4.0  1500.0            NaN
8       109        Ifeoma   Nigeria    None       2.0     NaN            4.0
9       110         Joyce     Ghana   Phone       NaN   800.0            5.0

In [3]:
#. TASK 1
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       10 non-null     int64
 1   Customer_Name  8 non-null      object
 2   Country        8 non-null      object
 3   Product        8 non-null      object
 4   Quantity       7 non-null      float64
 5   Price          8 non-null      float64
 6   Delivery_Days  7 non-null      float64
dtypes: float64(3), int64(1), object(3)
memory usage: 692.0+ bytes

In [4]:
df.describe()

        Order_ID  Quantity        Price  Delivery_Days
count   10.00000  7.000000     8.000000       7.000000
mean   105.50000  2.142857  1012.500000       4.714286
std      3.02765  1.069045   412.093956       1.496026
min    101.00000  1.000000   600.000000       3.000000
25%    103.25000  1.500000   750.000000       3.500000
50%    105.50000  2.000000   800.000000       5.000000
75%    107.75000  2.500000  1500.000000       5.500000
max    110.00000  4.000000  1500.000000       7.000000

In [5]:
df.isnull().sum()

Order_ID         0
Customer_Name    2
Country          2
Product          2
Quantity         3
Price            2
Delivery_Days    3
dtype: int64

TASK 1 - EXPLANATION : 
The dataset contains missing values in Customer_Name, Country, Product, Quantity, Price, and Delivery_Days.
Quantity and Delivery_Days have the highest number of missing values.
The data needs to be cleaned before analysis can be performed.

In [13]:
#TASK 2
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

df

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop       2.0  1500.0            3.0
1       102          Bola   Nigeria   Phone       1.0   800.0            NaN
2       103       Unknown     Kenya  Tablet       NaN   600.0            7.0
3       104         Diana      None  Laptop       3.0  1500.0            5.0
4       105          Efua     Ghana    None       2.0     NaN            3.0
5       106        Fatima  Cameroon   Phone       NaN   800.0            NaN
6       107         Grace      None  Tablet       1.0   600.0            6.0
7       108       Unknown     Kenya  Laptop       4.0  1500.0            NaN
8       109        Ifeoma   Nigeria    None       2.0     NaN            4.0
9       110         Joyce     Ghana   Phone       NaN   800.0            5.0

TASK 2- EXPANATION :
I filled the missing customer names with "Unknown" because the actual names cannot be recovered, but the orders are still useful and should remain in the dataset.

In [14]:
#. TASK 3
print("Mean Quantity:", df["Quantity"].mean())
print("Mean Price:", df["Price"].mean())

Mean Quantity: 2.142857142857143
Mean Price: 1012.5

In [15]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())

df["Price"] = df["Price"].fillna(df["Price"].mean())

df

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop  2.000000  1500.0            3.0
1       102          Bola   Nigeria   Phone  1.000000   800.0            NaN
2       103       Unknown     Kenya  Tablet  2.142857   600.0            7.0
3       104         Diana      None  Laptop  3.000000  1500.0            5.0
4       105          Efua     Ghana    None  2.000000  1012.5            3.0
5       106        Fatima  Cameroon   Phone  2.142857   800.0            NaN
6       107         Grace      None  Tablet  1.000000   600.0            6.0
7       108       Unknown     Kenya  Laptop  4.000000  1500.0            NaN
8       109        Ifeoma   Nigeria    None  2.000000  1012.5            4.0
9       110         Joyce     Ghana   Phone  2.142857   800.0            5.0

TASK 3- EXPLANATION :
For Quantity, I used the mean because the values are fairly close together and there are no extreme values.

For Price, I used the mean because the prices are reasonably balanced and there are no significant outliers.

In [16]:
#. TASK 4
df["Delivery_Days"].describe()

count    7.000000
mean     4.714286
std      1.496026
min      3.000000
25%      3.500000
50%      5.000000
75%      5.500000
max      7.000000
Name: Delivery_Days, dtype: float64

The delivery days range from 3 to 7 days, so there are no obvious outliers. Since the values are close together, the mean is an appropriate choice for filling the missing values.

In [17]:
df["Delivery_Days"] = df["Delivery_Days"].fillna(df["Delivery_Days"].mean())

df

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop  2.000000  1500.0       3.000000
1       102          Bola   Nigeria   Phone  1.000000   800.0       4.714286
2       103       Unknown     Kenya  Tablet  2.142857   600.0       7.000000
3       104         Diana      None  Laptop  3.000000  1500.0       5.000000
4       105          Efua     Ghana    None  2.000000  1012.5       3.000000
5       106        Fatima  Cameroon   Phone  2.142857   800.0       4.714286
6       107         Grace      None  Tablet  1.000000   600.0       6.000000
7       108       Unknown     Kenya  Laptop  4.000000  1500.0       4.714286
8       109        Ifeoma   Nigeria    None  2.000000  1012.5       4.000000
9       110         Joyce     Ghana   Phone  2.142857   800.0       5.000000

In [18]:
#. TASK 5
print("Country Mode:", df["Country"].mode()[0])
print("Product Mode:", df["Product"].mode()[0])

Country Mode: Ghana
Product Mode: Laptop

In [19]:
df["Country"] = df["Country"].fillna(df["Country"].mode()[0])

df["Product"] = df["Product"].fillna(df["Product"].mode()[0])

df

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop  2.000000  1500.0       3.000000
1       102          Bola   Nigeria   Phone  1.000000   800.0       4.714286
2       103       Unknown     Kenya  Tablet  2.142857   600.0       7.000000
3       104         Diana     Ghana  Laptop  3.000000  1500.0       5.000000
4       105          Efua     Ghana  Laptop  2.000000  1012.5       3.000000
5       106        Fatima  Cameroon   Phone  2.142857   800.0       4.714286
6       107         Grace     Ghana  Tablet  1.000000   600.0       6.000000
7       108       Unknown     Kenya  Laptop  4.000000  1500.0       4.714286
8       109        Ifeoma   Nigeria  Laptop  2.000000  1012.5       4.000000
9       110         Joyce     Ghana   Phone  2.142857   800.0       5.000000

TASK 5- EXPLANATION : 
I filled the missing Country values using the mode because Country is a categorical column and the most common value is a reasonable replacement.

I filled the missing Product values using the mode because Product is also a categorical column and using the most frequent product helps preserve the dataset.

In [20]:
#. TASK 6
df.isnull().sum()

Order_ID         0
Customer_Name    0
Country          0
Product          0
Quantity         0
Price            0
Delivery_Days    0
dtype: int64

TASK 6- EXPLANATION : 
The output shows that all columns now contain zero missing values, which means the dataset has been successfully cleaned.

#. TASK 7 - REFLECTION :
The hardest decision was choosing how to handle the Country and Product columns because there are different ways to deal with missing categorical data. I did not use the same method for every column because different data types require different cleaning techniques. For Customer_Name, I used "Unknown" because the missing information could not be recovered. For Quantity, Price, and Delivery_Days, I used the mean because the values were relatively balanced and had no major outliers. For Country and Product, I used the mode because they are categorical columns. This assignment helped me understand that data cleaning depends on the type of data and the problem being solved. If 50% of the Price values were missing, I would investigate the reason for the missing data before filling it because using the mean for a large amount of missing data could affect the accuracy of the analysis.