In [1]:
##SALES DATA
import pandas as pd

data = {
    "Order_ID": ["ORD001","ORD002","ORD003","ORD004","ORD005","ORD006","ORD007","ORD008","ORD009","ORD010"],
    "Product": ["Laptop","Rice Bag","Headphones","Notebook","Blender","Rice Bag","Laptop","Notebook","Blender","Headphones"],
    "Category": ["Electronics","Food","Electronics","Stationery","Appliances","Food","Electronics","Stationery","Appliances","Electronics"],
    "Region": ["North","South","East","West","North","East","South","North","West","North"],
    "Units_Sold": [5,30,12,50,8,20,3,80,6,15],
    "Unit_Price": [850.00,12.50,45.00,3.20,65.00,12.50,850.00,3.20,65.00,45.00],
    "Month": ["January","January","February","February","March","March","April","April","May","May"]
}

df = pd.DataFrame(data)

print(df)

  Order_ID     Product     Category Region  Units_Sold  Unit_Price     Month
0   ORD001      Laptop  Electronics  North           5       850.0   January
1   ORD002    Rice Bag         Food  South          30        12.5   January
2   ORD003  Headphones  Electronics   East          12        45.0  February
3   ORD004    Notebook   Stationery   West          50         3.2  February
4   ORD005     Blender   Appliances  North           8        65.0     March
5   ORD006    Rice Bag         Food   East          20        12.5     March
6   ORD007      Laptop  Electronics  South           3       850.0     April
7   ORD008    Notebook   Stationery  North          80         3.2     April
8   ORD009     Blender   Appliances   West           6        65.0       May
9   ORD010  Headphones  Electronics  North          15        45.0       May

In [2]:
##PART A. SELECTING COLUMNS

In [39]:
#1. ONLY PRODUCT AND REGION

df[["Product", "Region"]]

      Product Region
0      Laptop  North
1    Rice Bag  South
2  Headphones   East
3    Notebook   West
4     Blender  North
5    Rice Bag   East
6      Laptop  South
7    Notebook  North
8     Blender   West
9  Headphones  North

In [38]:
#2.DISPLAY ORDER_ID, CATEGORY AND UNITS_SOLD

df[["Order_ID", "Category", "Units_Sold"]]

  Order_ID     Category  Units_Sold
0   ORD001  Electronics           5
1   ORD002         Food          30
2   ORD003  Electronics          12
3   ORD004   Stationery          50
4   ORD005   Appliances           8
5   ORD006         Food          20
6   ORD007  Electronics           3
7   ORD008   Stationery          80
8   ORD009   Appliances           6
9   ORD010  Electronics          15

In [5]:
#.3
##SINGLE BRACKET
df["Unit_Price"]

0    850.0
1     12.5
2     45.0
3      3.2
4     65.0
5     12.5
6    850.0
7      3.2
8     65.0
9     45.0
Name: Unit_Price, dtype: float64

In [6]:
##DOUBLE BRACKET
df[["Unit_Price"]]

   Unit_Price
0       850.0
1        12.5
2        45.0
3         3.2
4        65.0
5        12.5
6       850.0
7         3.2
8        65.0
9        45.0

In [7]:
##DIFFERENCE 
type(df["Unit_Price"])

pandas.core.series.Series

In [8]:

##PART B. FILTERING ROWS

In [37]:
#4. NORTH REGION ONLY

df[df["Region"] == "North"]

  Order_ID     Product     Category Region  Units_Sold  Unit_Price    Month
0   ORD001      Laptop  Electronics  North           5       850.0  January
4   ORD005     Blender   Appliances  North           8        65.0    March
7   ORD008    Notebook   Stationery  North          80         3.2    April
9   ORD010  Headphones  Electronics  North          15        45.0      May

In [36]:
#5. UNITS_SOLD GREATER THAN 10

df[df["Units_Sold"] > 10]

  Order_ID     Product     Category Region  Units_Sold  Unit_Price     Month
1   ORD002    Rice Bag         Food  South          30        12.5   January
2   ORD003  Headphones  Electronics   East          12        45.0  February
3   ORD004    Notebook   Stationery   West          50         3.2  February
5   ORD006    Rice Bag         Food   East          20        12.5     March
7   ORD008    Notebook   Stationery  North          80         3.2     April
9   ORD010  Headphones  Electronics  North          15        45.0       May

In [35]:
#6. Electronics AND Units_Sold > 5

df[(df["Category"] == "Electronics") & (df["Units_Sold"] > 5)]

  Order_ID     Product     Category Region  Units_Sold  Unit_Price     Month
2   ORD003  Headphones  Electronics   East          12        45.0  February
9   ORD010  Headphones  Electronics  North          15        45.0       May

In [34]:
#7. SOUTH OR WEST

df[(df["Region"] == "South") | (df["Region"] == "West")]

  Order_ID   Product     Category Region  Units_Sold  Unit_Price     Month
1   ORD002  Rice Bag         Food  South          30        12.5   January
3   ORD004  Notebook   Stationery   West          50         3.2  February
6   ORD007    Laptop  Electronics  South           3       850.0     April
8   ORD009   Blender   Appliances   West           6        65.0       May

In [13]:

##.PART C. GROUPING DATA

In [33]:
#8. TOTAL UNITS_SOLD FOR EACH REGION

df.groupby("Region")["Units_Sold"].sum()

Region
East      32
North    108
South     33
West      56
Name: Units_Sold, dtype: int64

In [31]:
#9. AVERAGE UNIT_PRICE FOR EACH CATEGORY

df.groupby("Category")["Unit_Price"].mean()

Category
Appliances      65.0
Electronics    447.5
Food            12.5
Stationery       3.2
Name: Unit_Price, dtype: float64

In [30]:
#10. TOTAL UNITS_SOLD AND AVERAGE UNIT_PRICE
df.groupby("Category").agg({
    "Units_Sold": "sum",
    "Unit_Price": "mean"
})

             Units_Sold  Unit_Price
Category
Appliances           14        65.0
Electronics          35       447.5
Food                 50        12.5
Stationery          130         3.2

In [29]:
#11. TOTAL UNITS_SOLD PER MONTH

df.groupby("Month")["Units_Sold"].sum()

Month
April       83
February    62
January     35
March       28
May         21
Name: Units_Sold, dtype: int64

In [28]:
#12. REGION WITH HIGHEST UNITS_SOLD.

df.groupby("Region")["Units_Sold"].sum().idxmax()

'North'

In [19]:

##ANSWERING BUSINESS QUETIONS

In [27]:
#13. PRODUCTS WITH LOWEST AVERAGE UNIT_PRICE

df.groupby("Product")["Unit_Price"].mean().idxmin()

'Notebook'

In [26]:
#14. MONTH WITH HIGHEST UNITS_SOLD.

df.groupby("Month")["Units_Sold"].sum().idxmax()

'April'

In [24]:
#15. ELECTRONICS FROM NORTH REGION
df[
    (df["Category"] == "Electronics") &
    (df["Region"] == "North")
][["Product", "Units_Sold", "Unit_Price"]]

      Product  Units_Sold  Unit_Price
0      Laptop           5       850.0
9  Headphones          15        45.0

In [42]:
#.16
df.groupby('Category')['Total_Sales'].sum()

Category
Appliances      910.0
Electronics    8015.0
Food            625.0
Stationery      416.0
Name: Total_Sales, dtype: float64

In [43]:
df.groupby('Category')['Total_Sales'].sum().idxmax()

'Electronics'